FROM node:20-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps || npm install --legacy-peer-deps

COPY . .
COPY next.config.sponsor.ts next.config.ts

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

EXPOSE 3002

ENV PORT 3002
ENV HOSTNAME "0.0.0.0"
ENV NODE_ENV production

CMD ["npm", "start"]