FROM node:20-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps || npm install --legacy-peer-deps

COPY . .
COPY next.config.admin.ts next.config.ts

ENV NEXT_TELEMETRY_DISABLED 1
ENV NEXT_PUBLIC_APP_ROLE admin

RUN npm run build

EXPOSE 3003

ENV PORT 3003
ENV HOSTNAME "0.0.0.0"
ENV NODE_ENV production

CMD ["npm", "start"]