version: '3.8'

services:
  # データベース
  mysql:
    image: mysql:8.0
    container_name: hatamo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hatamo_db
      MYSQL_USER: hatamo_user
      MYSQL_PASSWORD: hatamo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hatamo_network
    restart: unless-stopped

  # Redis（セッション・キャッシュ用）
  redis:
    image: redis:7-alpine
    container_name: hatamo_redis
    ports:
      - "6379:6379"
    networks:
      - hatamo_network
    restart: unless-stopped

  # メインバックエンド（利用者・スポンサー用）
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hatamo_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://hatamo_user:hatamo_password@mysql:3306/hatamo_db
      - JWT_SECRET=your-super-secret-jwt-key
      - FRONTEND_URL=http://localhost:3000
      - ADMIN_BACKEND_URL=http://admin-backend:5001
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - hatamo_network
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  # 管理者用バックエンド
  admin-backend:
    build:
      context: ./admin-backend
      dockerfile: Dockerfile
    container_name: hatamo_admin_backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://hatamo_user:hatamo_password@mysql:3306/hatamo_db
      - JWT_SECRET=your-admin-super-secret-jwt-key
      - ADMIN_FRONTEND_URL=http://localhost:3001
      - MAIN_BACKEND_URL=http://backend:5000
    volumes:
      - ./admin-backend:/app
      - /app/node_modules
    networks:
      - hatamo_network
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  # フロントエンド（利用者・スポンサー用）
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: hatamo_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - hatamo_network
    depends_on:
      - backend
    restart: unless-stopped

  # 管理者用フロントエンド（将来的に追加予定）
  # admin-frontend:
  #   build:
  #     context: ./admin-frontend
  #     dockerfile: Dockerfile.dev
  #   container_name: hatamo_admin_frontend
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:5001/api
  #   volumes:
  #     - ./admin-frontend:/app
  #     - /app/node_modules
  #     - /app/.next
  #   networks:
  #     - hatamo_network
  #   depends_on:
  #     - admin-backend

  # データベース管理ツール
  adminer:
    image: adminer
    container_name: hatamo_adminer
    ports:
      - "8080:8080"
    networks:
      - hatamo_network
    depends_on:
      - mysql
    restart: unless-stopped

  # Nginx（リバースプロキシ・ロードバランサー）
  nginx:
    image: nginx:alpine
    container_name: hatamo_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - hatamo_network
    depends_on:
      - frontend
      - backend
      - admin-backend
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  hatamo_network:
    driver: bridge